package:
  name:
    affogato
  {% set tagged_version = GIT_DESCRIBE_TAG|replace("v","")|replace("-", ".") %}
  {% if GIT_DESCRIBE_NUMBER|int != 0 %}
    {% set tagged_version = tagged_version + '.post' + GIT_DESCRIBE_NUMBER %}
  {% endif %}
  version:
   0.2.3
#   {{tagged_version}}


source:
  path: ..


build:
  number: 0
  string: py{{py}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}


requirements:
  build:
    - python {{ python }}
    - cmake
    - boost >=1.63
    - xtensor-python
  run:
    - python {{ python }}
    - numpy # do not need to constrain np version


test:
  imports:
    - affogato
