name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: ${{ matrix.os }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # os: [macos-latest, windows-latest, ubuntu-latest]
        os: [macos-latest, ubuntu-latest]
        python-version: [3.12]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: .github/workflows/environment.yaml
          create-args: >-
            python=${{ matrix.python-version }}

      # this will set the system compiler;
      # I don't know how to set the conda compilers for windows
      - name: Set windows env
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build linux
        if: matrix.os == 'ubuntu-latest'
        shell: bash -l {0}
        run: .github/workflows/build_unix.sh

      - name: Build mac
        if: matrix.os == 'macos-latest'
        shell: bash -l {0}
        run: .github/workflows/build_unix.sh

      - name: Build win
        if: matrix.os == 'windows-latest'
        shell: bash -l {0}
        run: .github/workflows/build_win.bat

      # run full tests on mac and linux
      - name: Run tests linux
        if: matrix.os == 'ubuntu-latest'
        shell: bash -l {0}
        run: python -m unittest discover -s src/python/test -v
      - name: Run tests mac
        if: matrix.os == 'macos-latest'
        shell: bash -l {0}
        run: python -m unittest discover -s src/python/test -v

    # only run tests for mutex watershed on windows to avoid other test failures
      - name: Run tests win
        if: matrix.os == 'windows-latest'
        shell: bash -l {0}
        run: python src/python/test/segmentation/test_mutex_watershed.py
